### ISSUE TITLE
SendBirdGroupChannel response is incorrectly typed

### ISSUE THREAD

**Issue by pmdevita** [sendbird/sendbird-platform-sdk-python#11]
SendBirdGroupChannel's OpenAPI type is incorrect. The SendBirdGroupChannel model's `inviter` attribute is typed to be the `SendBirdUser` model, but does not allow for null values, and validation fails if the API returns null for this field. This breaks `gc_list_channels` and probably any other call that responds with this data type.

**Comment by june-xpace** [comment]
I am currently using version 1.0.14 due to the same issue.
I hope this problem gets resolved soon.

**Comment by 6691a** [comment]
I am currently using version 1.0.14 due to the same issue.
I hope this problem gets resolved soon.

**Comment by pmdevita** [comment]
Fixed in ebf3e66a7e5b3589d47c46705efd0f2ac2d1ed38
