### ISSUE TITLE
Positional arguments missing error for optional fields

### ISSUE THREAD

**Issue by gangeshwark** [sendbird/sendbird-platform-sdk-python#3]
Hi,
I am unable to create a group channel with default values, I encounter this error

```
  File "/Users/gangeshwark/projects/MindFi/mindfi-backend/app/sendbird_helpers.py", line 100, in create_chat_channel
    user_ids=person_ids_str,
  File "/Users/gangeshwark/.conda/envs/mindfi-backend/lib/python3.6/site-packages/sendbird_platform_sdk-1.0.5-py3.6.egg/sendbird_platform_sdk/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: __init__() missing 18 required positional arguments: 'users', 'name', 'channel_url', 'cover_url', 'cover_file', 'custom_type', 'data', 'is_distinct', 'is_public', 'is_super', 'is_ephemeral', 'access_code', 'inviter_id', 'strict', 'invitation_status', 'hidden_status', 'operator_ids', and 'block_sdk_user_channel_join'

```

For the code below:

```

    def create_chat_channel(self, person_ids: List):
        person_ids = sorted(person_ids)
        person_ids_str = [str(x) for x in person_ids]
        gc_create_channel_data = GcCreateChannelData(
            user_ids=person_ids_str,
        )  # GcCreateChannelData |  (optional)

        # example passing only required values which don't have defaults set
        # and optional values
        try:
            # Create a channel
            api_response = self.gc_api_instance.gc_create_channel(self.api_token,
                                                                  gc_create_channel_data=gc_create_channel_data)
            pprint(api_response)
            return api_response
        except sendbird_platform_sdk.ApiException as e:
            print("Exception when calling GroupChannelApi->gc_create_channel: %s\n" % e)
            return {}

```

The API Documentation says that ONLY user_ids are mandatory and the rest are optional. 
https://sendbird.com/docs/chat/v3/platform-api/channel/creating-a-channel/create-a-group-channel#1-create-a-group-channel

How do I create a group channel with default values? 

Thank you!

**Comment by james-a-rob** [comment]
Hi @gangeshwark

Thanks for reporting this. Its something we can get fixed up for you.

Just to give a little background on how these sdks are built...
They are made from our [open api spec](https://github.com/sendbird/sendbird-platform-openapi) using language specific [generators](https://github.com/OpenAPITools/openapi-generator). 

There does appear to be an oversight in our open api spec that is causing the python SDK to require more arguments than required. I have located the issue and have a fix ready. I am just doing some locally testing to confirm this all works as expected. I should have a new release for you in a few hours. 

I will drop a message here when I release.

**Comment by gangeshwark** [comment]
Thanks @james-a-rob look forward to the update :)
Right now I am just using requests lib to make the API call.

**Comment by james-a-rob** [comment]
Version 1.0.6 is released and should fix your issue.

https://github.com/sendbird/sendbird-platform-sdk-python/releases/tag/1.0.6

If you find any other issues please let me know. With these Open API based SDKs most bugs can be fixed quite easily. It's often just a quick config change.

**Comment by ramatronics** [comment]
@james-a-rob thank you for the quick turnaround!!
