### ISSUE TITLE
SSL Handshake Error; is there an option to set verify=False?

### ISSUE THREAD

**Issue by ramatronics** [sendbird/sendbird-platform-sdk-python#4]
```
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-dontmatter.sendbird.com', port=443): Max retries exceeded with url: /v3/users/resultant-lepton-e/unread_channel_count (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

I see some stuff in `configuration` to turn off SSL verification, but can't quite figure it out.

**Comment by james-a-rob** [comment]
Thanks for the question @ramatronics.

I can see from the error above that your Sendbird app id is set to `dontmatter`. That is not a valid Sendbird app ID. 
If I set my app id locally to  `dontmatter` I can replicate your exact issue. Your Sendbird app id can be found in the Sendbird dashbaord app settings page. Just set that and you should be all good to go.

Let me know if that still doesnt solve your issue. I can have a deeper look at how the python SDK configuration works if disabling ssl verification is absolutely required for your use case.

**Comment by ramatronics** [comment]
I did set the right app-id. I just replaced it with `dontmatter` because I didn't want to put my app ID out. But I can assure you I tried the right app-id, im supposed to enter the full hostname in the format of the following, correct?

```
configuration = sendbird_platform_sdk.Configuration(
    host = "https://api-YOUR_APP_ID_FROM_DASHBOARD.sendbird.com"
)
```

**Comment by james-a-rob** [comment]
Ah ye thats good thinking. Let me investigate a bit more.

**Comment by james-a-rob** [comment]
Im really hoping there is a way we can get this working without disabling cert verfication as not so secure.

May I ask what version of python you are using?
I am testing the SDk against running 3.9.10.

There are some versions of py that dont include certs aparently https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
