### ISSUE TITLE
Getting list of channels for application shows created_by set to null and is_discoverable set to false.

### ISSUE THREAD

**Issue by mansinarain** [sendbird/sendbird-platform-sdk-python#6]
Hi! 
I'm passing the following info to create a group channel - but when i use the postmanAPI to get the application channels - i see created_by set to false and is_discoverable set to false. If i try getting the group channels for a user - by used id - i am getting an empty array. Please help!

```
gc_create_channel_data = GcCreateChannelData(
                user_ids=[
                    "OtterOps1",
                    sendbird_user.user_id,
                ],
                name="Otter Support Team",
                channel_url="sendbird_ops_support_channel_{}".format(user_in.id),
                custom_type="support",
                is_distinct=True,
                is_public=False,
                is_super=False,
                is_ephemeral=False,
                created_by=sendbird_user,
                invitation_status={
                    "OtterOps1": "joined",
                    sendbird_user.user_id: "joined",
                },
            )  # GcCreateChannelData |  (optional)

            try:
                # Create a channel
                api_instance.gc_create_channel(
                    settings.SENDBIRD_MASTER_TOKEN,
                    gc_create_channel_data=gc_create_channel_data,
                )
```

                
            
            sendbird_user here maps to ->
           ```
 return SendBirdUser(
              user_id=str(user_in.id),
              nickname=user_in.first_name or "",
              profile_url="",
              issue_access_token=True,
              metadata=({}),
              role="none",
              require_auth_for_profile_image=False,
          )
```
          
        Here is the postman API Response :
        
```
        {
    "channels": [
        {
            "channel_url": "sendbird_ops_support_channel_5",
            "name": "Otter Support Team",
            "cover_url": "https://static.sendbird.com/sample/cover/cover_14.jpg",
            "data": "",
            "member_count": 2,
            "joined_member_count": 2,
            "max_length_message": 5000,
            "created_at": 1664175375,
            "custom_type": "support",
            "is_distinct": true,
            "is_super": false,
            "is_broadcast": false,
            "is_public": false,
            "is_discoverable": false,
            "freeze": false,
            "is_ephemeral": false,
            "unread_message_count": 0,
            "unread_mention_count": 0,
            "ignore_profanity_filter": false,
            "channel": {
                "channel_url": "sendbird_ops_support_channel_5",
                "name": "Otter Support Team",
                "cover_url": "https://static.sendbird.com/sample/cover/cover_14.jpg",
                "data": "",
                "created_at": 1664175375,
                "custom_type": "support",
                "max_length_message": 5000,
                "member_count": 2
            },
            "created_by": null,
            "disappearing_message": {
                "is_triggered_by_message_read": false,
                "message_survival_seconds": -1
            },
            "is_access_code_required": false,
            "is_exclusive": false,
            "message_survival_seconds": -1,
            "sms_fallback": {
                "wait_seconds": -1,
                "exclude_user_ids": []
            },
            "inviter": null,
            "invited_at": 0,
            "last_message": null,
            "joined_ts": null
        }
    ],
    "next": "",
    "ts": 1664175386208
}
```

**Comment by mansinarain** [comment]
For api request - /v3/users/:userid/my_group_channels

i am getting ->
{
    "channels": [],
    "next": "",
    "ts": 1664175637821
}

**Comment by mansinarain** [comment]
@james-a-rob - just the userid - /v3/users/:userid/my_group_channels  -> the same userid i also passed in the created_by user

**Comment by james-a-rob** [comment]
Hey @mansinarain I have done some testing at my end and believe I have found a number of helpful pieces of information for you.

1. I investigated more deeply for the platform API works in regard to created_by. That field is in-fact set by the inviter_id. The SDK correctly models that behaviour. I did a quick local check using the gc_create_channel method and setting inviter_id. I can see created by set correctly .
2.  When retrieving all group channels with the list_my_group_channels method the default is to ignore any channels that have no messages. For me that was the case so I did too see an empty array. Once I called the method like so ``api_instance.list_my_group_channels(api_token, user_id, show_empty=True)`` I would see my channels array populated. From the above JSON response I see  last message is set to null so you too will need to set ```show_empty=Trueshow_empty=True```.
3. During these investigations I noticed a potentially related bug in parsing the channel response data. I have released a fix for that available in v12. If you could give the above a go with the latest code and let me know  that works for you. Happy to assist more if necessary. https://github.com/sendbird/sendbird-platform-sdk-python/releases/tag/0.0.12

**Comment by mansinarain** [comment]
Thank you @james-a-rob ! Will try this solution out. Really appreciate the quick fix
